version: 2.1
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/working-dir/workspace
executors:
  node_executor:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/mongo:latest
        environment:
          MONGODB_USERNAME: "test"
          MONGODB_PASSWORD: "test"
    working_directory: ~/working-dir
  node_executor_angular:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/working-dir
commands:
  test_express:
    description: "A command that tests express."
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - v1-dependencies-express {{ checksum "workspace/repo/express/package-lock.json" }}
      - run:
          name: npm install
          command: |
            cd workspace/repo/express
            npm install
      - save_cache:
          paths:
            - workspace/repo/express/node_modules
          key: v1-dependencies-express {{ checksum "workspace/repo/express/package-lock.json" }}
      - run:
          name: Create Dummy Config File
          command: >
            echo '{"port": 4000, "mongoDB": "mongodb://127.0.0.1:27017/test", "accessTokenSecret": "What is it my dears?", "apiPath": "/api/v1" }' > workspace/repo/express/config.json
      - run: |
          cd workspace/repo/express
          npm test
  test_angular:
    description: "A command that tests angular project."
    steps:
      - *attach_workspace
      - run:
          name: set-user-permissions
          command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
      - restore_cache:
          keys:
            - v3-dependencies-angular {{ checksum "workspace/repo/angular/FacilityMgt/package-lock.json" }}
      - run:
          name: Install @angular/cli
          command: sudo npm install -g @angular/cli@latest > /dev/null
      - run:
          name: npm install
          command: |
            cd workspace/repo/angular/FacilityMgt
            npm install
      - run:
          name: ng build
          command: |
            cd workspace/repo/angular/FacilityMgt
            ng build
      - save_cache:
          paths:
            - workspace/repo/angular/FacilityMgt/node_modules
            - /usr/local/lib/node_modules
          key: v3-dependencies-angular {{ checksum "workspace/repo/angular/FacilityMgt/package-lock.json" }}
jobs:
  checkout_code:
    executor: node_executor
    steps:
      - checkout:
          path: workspace/repo
      - persist_to_workspace:
          root: workspace
          paths:
            - repo
  test_express_project:
    executor: node_executor
    steps:
      - test_express
  test_angular_project:
    executor: node_executor_angular
    steps:
      - test_angular
workflows:
  version: 2
  main:
    jobs:
      - checkout_code
      - test_express_project:
          requires:
            - checkout_code
      - test_angular_project:
          requires:
            - checkout_code
