version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/repo/express
    steps:
      - checkout:
          path: ~/repo
      - node/with-cache:
          steps:
            - run: npm install
            - run: |
              echo '{"port": 4000, "mongoDB": "mongodb://test:test@localhost/test?retryWrites=true", "accessTokenSecret": "What is it my dears?", "apiPath": "/api/v1" }' > config.json
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test