version: 2.1
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/working-dir/workspace
executors:
  node_executor:
    docker:
      - image: circleci/node:12.16.1
      - image: circleci/mongo:latest
        environment:
          MONGODB_USERNAME: "test"
          MONGODB_PASSWORD: "test"
    working_directory: ~/working-dir
commands:
  build_project:
    description: "A command that tests express and builds the angular project."
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - v1-dependencies {{ checksum "workspace/repo/package-lock.json" }}
      - run:
          name: npm install
          command: |
            cd workspace/repo
            npm install
      - run:
          name: npm run build
          command: |
            cd workspace/repo
            npm run build
      - run: sudo apt-get install tree
      - run: tree -I 'node_modules|cache|test_*'
      - save_cache:
          paths:
            - workspace/repo/node_modules
          key: v1-dependencies {{ checksum "workspace/repo/package-lock.json" }}
      - run:
          name: Create Dummy Secrets Config File
          command: >
            echo '{"mongoDB": "mongodb://127.0.0.1:27017/test", "accessTokenSecret": "What is it my dears?" }' > workspace/repo/express/secrets.json
      - run:
          name: Test Express
          command: |
            cd workspace/repo
            npm run test_express
      - run:
          name: Compress Artifacts
          command: |
            cd workspace/repo
            tar -cvf dist.tar dist
      - store_artifacts:
          path: workspace/repo/dist.tar
          destination: dist_artifact.tar
jobs:
  checkout_code:
    executor: node_executor
    steps:
      - checkout:
          path: workspace/repo
      - persist_to_workspace:
          root: workspace
          paths:
            - repo
  build_angular_project:
    executor: node_executor
    steps:
      - build_project
workflows:
  version: 2
  main:
    jobs:
      - checkout_code
      - build_angular_project:
          requires:
            - checkout_code
