name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: eendo@miu.edu
        heroku_app_name: miu-facility-management
        # An optional buildpack to use when creating the heroku application
        #buildpack: # optional
        # The branch that you would like to deploy to Heroku
        #branch: # optional, default is HEAD
        # Set this to true if you don't want to use --force when switching branches
        #dontuseforce: # optional
        # Will deploy using Dockerfile in project root.
        #usedocker: # optional
